# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: '#about'
    weight: 10
  - name: Blog
    url: '/blog'
    weight: 20
  # - name: Resume
  #   url: '/resume'
  #   weight: 30
